### ISSUE TITLE
Adding rangeIncludes URL to reference value vocabularies

### ISSUE THREAD

**Issue by stuartasutton** [dcmi/lrmi#1]
Currently properties that could reference vocabulary terms have a rangeIncludes of literal (schema.org/Text / http://www.w3.org/2001/XMLSchema#string)--educationalRole, educationalUse, interactivityType, and learningResourceType). Addtion of rangeIncludes of http://schema.org/URL to these properties would support reference concepts in SKOS-encoded concept schemes.

**Comment by stuartasutton** [comment]
Phil emailed separately on this same issue in the Feb. 19th call agenda and states:

>"I think it should be schema:Thing (some subtype thereof) rather than schema:URL.  http://schema.org/URL is a datatype for a property. It's not the same as the identifier of the property in RDF terms, typically it is the URL of a web page about the thing being described. For the uses you describe the most precise and accurate type of thing would be http://schema.org/Enumeration.

**Comment by stuartasutton** [comment]
Phil, I am a bit confused (maybe a lot confused) around the use of http://schema.org/Enumeration. When I look at something like https://schema.org/MusicAlbumReleaseType (an enumeration), I get a specific (enumerated) set of values. My intention was not necessarily to specify one specific concept scheme but a class of applicable concept schemes.  For example, we have the property learningResourceType (http://dublincore.org/dcx/lrmi-terms/#learningResourceType). It seems to me that we can either: (1) 'enumerate' a specific set of values as a sole recommendation; or (2) say that values must come from a concept scheme defined as a member of the class LearningResourceTypeVocabs. I'm **not** suggesting that either is the correct result for this particular property, but to try and ferret out the distinction. There would be one place for sure that the latter would be the case *if* we had an educationalLevel property like Dublin Core (http://dublincore.org/documents/dcmi-terms/#terms-educationLevel) where national concept schemes for denoting things like the U.S. notion of grade level vary significantly among nations. So, with a schema that must serve all nations, saying that values from an instance of the class EducationalLevelVocabs would be the best that could be done.

So, in an LRMI/schema.org world, how is this distinction expressed (at schema level).

**Comment by stuartasutton** [comment]
Unintentionally "closed" this issue

**Comment by philbarker** [comment]
Still a relevant issue, but now we have [DefinedTerm](https://schema.org/DefinedTerm), which might be a better range (or even skos:Concept if we want to be independent of schema.org's long pending decision about whether to fully embrace DefinedTerm)

**Comment by philbarker** [comment]
schema:DefinedTerm and skos:Concept added to appropriate ranges in 2020 LRMI Update
