### ISSUE TITLE
Create LearningResource class

### ISSUE THREAD

**Issue by stuartasutton** [dcmi/lrmi#11]
To date, LRMI has never defined LearningResource as a class. 

Some resource (thing) that:
(1) Signals its educational intention (i.e., through use the LRMI properties ); and
(2) Is fixed (recorded) in a tangible medium of expression by which it can be later perceived.

**Comment by philbarker** [comment]
I think that we should **not** do this. As far as I am concerned our not having done so already is deliberate. Reasons:
1. the definition of an educational resource is problematic. The approach we have taken is that any Creative Work can be an educational resource if its use as one can be described. I am uneasy with something becoming a new category of thing as a result of how it is used or described (or worse, how its use is described).
2. Assigning multiple types to resources seems poorly supported (and/or rarely tried) in schema.org. for example, doing so seems to cause the Yandex validator to signal errors. So do we create an "Educational[Video|Book|Article|...]" class for those learning resources that are videos/books/articles?
3. It solves no problem. You can already tell that something is used/intended as an learning resource by the presence of appropriate LRMI properties.
4. It creates a danger of many resources being inappropriately marked up as LearningResources for marketing reasons without any LRMI metadata being provided. What would an enterprising publisher wanting their resource to be used in education not tag as a LearningResource? (They can already do this by, for example, using learningResourceType = "newspaper" or "text", but let's not make it obvious.)

**Comment by philbarker** [comment]
OK. I changed my mind.

Related issue on schema.org is https://github.com/schemaorg/schemaorg/issues/1401

**Comment by philbarker** [comment]
done in 2020 LRMI Update
