### ISSUE TITLE
Problems with serving website on the local machine

### ISSUE THREAD

**Issue by acka47** [dcmi/lrmi#16]
When I follow the instructions at https://github.com/dcmi/lrmi/tree/master/webroot#serving-the-website-on-your-local-machine-with-hugo, I only see a blank page in the browser. And I get the following warning:

> Your rendered home page is blank: /index.html is zero-length

I don't know what is going wrong there...

**Comment by acka47** [comment]
Looking around on the web, I could not find a solution. The machine is running Linux Mint 18.1 (based on Ubuntu 16.04).

**Comment by stuartasutton** [comment]
@paulwalk, any thoughts?

**Comment by paulwalk** [comment]
I am not able to reproduce this error. I have tried Hugo v0.32.3 (the version running on the server) and v0.37 (the latest version).

Can you tell me what version of Hugo you are using?

**Comment by acka47** [comment]
I first installed hugo via Ubuntu ppa and got quite an old version (0.16 or so from 2016) from there. Now downloaded and installed the newest .deb package (version 0.37) and it works fine. Thanks for the hint, @paulwalk. Closing.

**Comment by paulwalk** [comment]
OK - glad that resolved it! I have added a note about checking the version of Hugo to the instructions at [https://github.com/dcmi/lrmi/tree/master/webroot#serving-the-website-on-your-local-machine-with-hugo](https://github.com/dcmi/lrmi/tree/master/webroot#serving-the-website-on-your-local-machine-with-hugo)
