### ISSUE TITLE
Re-enable redirect from lrmi.net to http://lrmi.dublincore.org

### ISSUE THREAD

**Issue by acka47** [dcmi/lrmi#18]
The 301 redirect from http://lrmi.net to http://lrmi.dublincore.org doesn't work anymore instead the content from http://dublincore.org/ is served at http://lrmi.net.

**Comment by stuartasutton** [comment]
@paulwalk, is the result of changing the Network Solutions redirect?

**Comment by paulwalk** [comment]
Ah - the redirect is working from www.lrmi.net only - I can fix this easily but not able to do it from my phone so will have to be later today when I get to a computer with an ssh client

**Comment by paulwalk** [comment]
I have fixed this now - both lrmi.net and www.lrmi.net redirect to lrmi.dublincore.org.

Thanks for reporting this!
