### ISSUE TITLE
Adding domainIncludes of Event as well as CreativeWork

### ISSUE THREAD

**Issue by stuartasutton** [dcmi/lrmi#2]
Consideration should be given to adding as domain (i.e., domainIncludes) schema.org/Event to all properties that currently have schema.org/CreativeWork:
- educationalAlignment 
- educationalUse
- interactivityType
- isBasedOnUrl
- learningResourceType
- timeRequired
- typicalAgeRange
- useRightsUrl

**Comment by stuartasutton** [comment]
More specifically, given that any of the LRMI properties 'purposes' an event as an Educational Event,  perhaps the target is not /Event but /EducationalEvent.

**Comment by philbarker** [comment]
We've considered this and taken action, see schema.org Issue [2427](https://github.com/schemaorg/schemaorg/issues/2427) and PR [2428](https://github.com/schemaorg/schemaorg/pull/2428)
