### ISSUE TITLE
[New Learning resource type] Physical objects

### ISSUE THREAD

**Issue by philbarker** [dcmi/lrmi#28]
### What would you like added
Physical Learning Resource.

Physical objects (other than information resources like books) that are intentionally designed to help a person learn something.

### Examples
Manipulables, e.g. [Cuisinaire rods](http://www.cuisenaire.co.uk/) 
hardware such as [speak-and-spell computers](https://en.wikipedia.org/wiki/Speak_%26_Spell_(toy)) 

### Is this a type of learning resource
**Is this type of resource specifically designed for teaching/learning?**
Yes

**Does your suggestion describe one of the following:**
No 

## Relationship to other resource types
**Is it possible to use one of the existing types as a broader classification for this type of resource?**
No 

**Would one of the existing types be a narrower classification for some resources of this type?**
No 

**Are there any related resource types in other schemes you use?**
don't know

**Additional context**
Channeling Josh

**Comment by stuartasutton** [comment]
Then we need to try through a comment to drive home that the notion of "physical object **_designed_** to help a person learn something" does not include objects of otherwise general use or even those deemed necessary "supplies" for a learning activity such as paper, pencils, calculators--i.e., necessary tools, instruments, supplies.

**Comment by philbarker** [comment]
Need examples of what is included and what is not (as comment).
Need to be clear that this does not include ancilliary materials.
Need examples showing how to reference resources needed for lesson, e.g. knives.

**Comment by stuartasutton** [comment]
+1 Phil with the following notes:  (1) "acheive" should be "achieve"; and (2) consider "achieve a" to achieve some".

The scope note leads me to wonder whether there might be a reasonable need for an "ancilliaryResource" property to cover "Supplies necessary to the effective outcome of the learning objective such as pencil, paper, scissors, soldering iron, calculator."  If so, the scope note second sentence for physicalLearningResource could point to "ancilliaryResource" property with something like the following text: "For ancillary resources such as pencil, paper, scissors, soldering iron, calculator necessary to the effective outcome of the learning objective, use the ancilliaryResource property.

**Comment by philbarker** [comment]
Thanks Stuart. I fixed the type and will raise an issue about `ancilliaryResource` so that comment doesn't get lost when we close this issue.

I wonder if  `... achieve one or more learning objectives.` would be best?

**Comment by philbarker** [comment]
Consensus on 2 Nov call to add this concept (pending editorialization)
