### ISSUE TITLE
Addition of LRMI properties to schema.org/EducationalEvent

### ISSUE THREAD

**Issue by stuartasutton** [dcmi/lrmi#9]
If we look at the schema.org type Event and compare it to its sub-type EducationalEvent, we see that they absolutely identical--they have the **_exact same properties**_. Having a rather formal bent in this regard, I think there must be some characteristic(s) that distinguish the class from the subclass. IMHO, the basic difference between an instance of Event and an instance of An EducationalEvent is that the latter _should explicitly state it's educational intentions_ through inclusion of LRMI properties--that is what LRMI was designed to do. That currently is not the case.

So, I suggest that we propose that Educational Event be amended to include the following properties:
- educationalAlignment
- educationalUse
- interactivityType

And, the domainIncludes of these properties should be amended to include both CreativeWork and EducationalEvent.

Event (and Educational Event) already have typicalAgeRange.

I do not think that learningResourceType is an appropriate addition to EducationalEvent since events are inherently ephemeral. Note that both Event and EducationalEvent have a recordedIn property with a rangeIncludes of CreativeWork. And CreativeWork (and thus a learning resource) has an inverse property recordedAt. A learning resource (i.e., CreativeWork) is thus created through fixing of the ephemeral EducationalEvent in a tangible medium of expression that can be later expressed and communicated. So it is the CreativeWork resulting from a fixing of the EducationalEvent that should (and does already) have a learningResourceType property.

After a little discussion here would be useful before going further.

**Comment by jmarks** [comment]
Stewart,

+1 for everything your wrote.

My only additional thought is how this Event might interact or be used in
conjunction or within a leaning management context where the educational
event might be assigned (go see this play), or executed (Perform this piano
concerto). The distinction between the ephemeral event and the tangible
output of that event is interesting and helpful. Otherwise, I have nothing
to add.

Joshua

**Comment by philbarker** [comment]
See schema.org PR [2428](https://github.com/schemaorg/schemaorg/pull/2428)

**Comment by philbarker** [comment]
Schema.org release 8 added [assesses](https://schema.org/assesses), [teaches](https://schema.org/teaches), and [educationalLevel](https://schema.org/teaches)
